name: Tests and Release

on:
  workflow_call:
    inputs: 
      pharo-versions:
        required: false
        type: string
      image-name:
        required: false
        type: string
      pre-upload-script:
        required: false
        type: string
      create-artifact:
        required: false
        type: boolean
      run-coverage:
        required: false
        type: boolean

jobs:

  common-parameters:
    runs-on: ubuntu-latest
    name: Set common parameters
    outputs:
      branch-name: ${{ steps.branch-name.outputs.branch-name }}
      image-name: ${{ steps.image-name.outputs.image-name }}
    steps:
      - name: Branch name
        id: branch-name
        run: >-
          echo branch-name=${{ (github.event_name == 'push' && github.ref_name)
          || (github.event_name == 'pull_request' && github.base_ref) 
          || (github.event_name == 'release' && github.github.event.release.target_commitish) }}
          >> $GITHUB_OUTPUT

      - name: Image name
        id: image-name
        run: >-
          echo image-name=${{ inputs.image-name 
          || (vars.BRANCHES_CONFIGURATION && fromJSON(vars.BRANCHES_CONFIGURATION)[steps.branch-name.outputs.branch-name].image-name)
          || format('{0}-{1}', github.event.repository.name, steps.branch-name.outputs.branch-name) }}
          >> $GITHUB_OUTPUT
  
  run-tests:
    name: Run tests
    needs: common-parameters
    uses: ./.github/workflows/run-tests-step.yml
    with:
      image-name: ${{ needs.common-parameters.outputs.image-name }}
      pharo-versions: ${{ inputs.pharo-versions }}
      pre-upload-script: ${{ inputs.pre-upload-script }}
      create-artifact: ${{ inputs.create-artifact }}
      run-coverage: ${{ inputs.run-coverage }}
      branch-name: ${{ needs.common-parameters.outputs.branch-name }}
