name: Run tests

on:
  workflow_call:
    inputs: 
      pharo-versions:
        required: false
        type: string

env:
  PV: ${{ inputs.pharo-versions }}
  MV: ${{ fromJSON(vars.MOOSE_PHARO_VERSIONS)['Moose-latest'] }}
  BRANCH_V: ${{ vars.BRANCHES_CONFIGURATION && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name] || 'Test' }}
#  BRANCH_V_M: ${{ fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name].moose-version }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Run on the images provided as input. If no images were provided (empty string) run on the default versions.
        # Default versions are computed using repository variables:
          # If a specific Moose version was set for the target branch: the Pharo images associated with this Moose version
          # Else the Pharo images asociated with Moose-latest.
        smalltalk: [ Pharo64-12 ] # ${{ fromJSON(inputs.pharo-versions || fromJSON(vars.MOOSE_PHARO_VERSIONS)[fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name].moose-version || 'Moose-latest']) }} # The warning is wrong.
    name: ${{ matrix.smalltalk }}
    steps:
    
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Option fetching all commits
      - name: Set-up smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
