name: Tests and Release

on:
  workflow_call:
    inputs:
      image-name:
        required: false
        type: string
      pharo-versions:
        required: false
        type: string
      pre-upload-script:
        required: false
        type: string
      release-tag:
        required: false
        type: string
      run-coverage:
        required: false
        type: boolean

jobs:
  run-tests:
    name: Run tests
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    with:
      image-name: ${{ inputs.image-name }}
      pharo-versions: ${{ inputs.pharo-versions }}
      pre-upload-script: ${{ inputs.pre-upload-script }}
      create-artifact: true
      run-coverage: ${{ inputs.run-coverage }}

  update-release:
    name: Update ${{ inputs.release-tag }} release
    needs: run-tests
    uses: moosetechnology/.github/.github/workflows/update-release.yml@main
    with:
       image-name: ${{ inputs.image-name }}
       release-tag: ${{ inputs.release-tag }}
