name: Update Release

on:
  workflow_call:
    inputs: 
      image-name:
        required: false
        type: string
      release-tag:
        required: false
        type: string
      branch-name:
        required: true
        type: string

jobs:
  update-release-with-new-artifacts:
    name: Update ${{ inputs.release-tag }} release with new artifacts
    runs-on: ubuntu-latest  
    steps:

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.image-name }}*
      
      - name: Zip files
        # Zip the downloaded files.
        # Store a string variable: the zip files names separated by semicolons.
        id: zip-files
        run: |
          for i in ${{inputs.image-name}}*; do zip -r "${i%/}.zip" "$i"; done
          echo files-names=$(ls -m ${{inputs.image-name}}*.zip) | sed -e 's/, /;/g' >> $GITHUB_OUTPUT
      
      - name: Update release
        uses: Xotl/cool-github-releases@v1 # See https://github.com/actions-marketplace-validations/Xotl_cool-github-releases
        with:
          mode: update
          replace_assets: true
          tag_name:  >-
            ${{ inputs.release-tag 
            || vars.BRANCHES_CONFIGURATION && fromJSON(vars.BRANCHES_CONFIGURATION)[inputs.branch-name].release-tag 
            || 'generated-assets' }}
              
          assets: ${{ steps.zip-files.outputs.files-names }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
